services:
  db:
    container_name: mysql-profitmap
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: profitmap
    ports:
      - "53306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
